spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: 7723
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: "kenguru"
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQL10Dialect"
